/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation(project(":bo-framework-core-mapper"))
    implementation("ma.glasnost.orika:orika-core:1.5.4")
    implementation("org.springframework:spring-context:6.0.0-RC4")
    implementation(project(":bo-framework-spring-support-core"))
    implementation(project(":bo-framework-orika-mapper"))
    implementation(project(":bo-framework-repository"))
    implementation("org.springframework:spring-beans:6.0.0-RC4")
    implementation("org.springframework.boot:spring-boot-autoconfigure:3.0.0-RC2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.mockito:mockito-core:4.9.0")
}

description = "orika-mapper-spring"
