/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation(project(":bo-framework-repository"))
    implementation(project(":bo-framework-query"))
    implementation(project(":bo-framework-exception-handling-core"))
    implementation(project(":bo-framework-validation-core"))
}

description = "businessapi"
