/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
    id("org.gradlex.extra-java-module-info") version "1.1"
}



extraJavaModuleInfo {
    // This does not have to be a complete description (e.g. here 'org.apache.commons.collections' does not export anything here).
    // It only needs to be good enough to work in the context of this application we are building.
    module("commons-beanutils:commons-beanutils", "org.apache.commons.beanutils") {
        exports("org.apache.commons.beanutils")
        requires("org.apache.commons.logging")
    }
    module("commons-collections:commons-collections", "org.apache.commons.collections")
    automaticModule("commons-logging:commons-logging", "org.apache.commons.logging")
}



dependencies {
    implementation(project(":bo-framework-exception-handling-core"))
    implementation("org.javassist:javassist:3.29.2-GA")
    implementation("commons-beanutils:commons-beanutils:1.9.4")
    implementation("org.slf4j:slf4j-api:2.0.3")
    implementation("net.bytebuddy:byte-buddy:1.12.19")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.hamcrest:hamcrest:2.2")
    testImplementation("ch.qos.logback:logback-classic:1.4.4")
    testImplementation("org.mockito:mockito-core:4.9.0")
}

description = "dynamic"
