language: java
sudo: false
install: true
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: divyakumarjain-github
    token:
      secure: 882041644b43f437f2ca990154b379269bd51112
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false

