/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation("com.fasterxml.jackson.module:jackson-module-parameter-names:2.14.0-rc3")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.14.0-rc3")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.0-rc3")
    implementation(project(":bo-framework-endpoint-jersey"))
    implementation(project(":bo-framework-spring-support-core"))
    implementation(project(":bo-framework-dynamic"))
    implementation(project(":bo-framework-repository"))
    implementation(project(":bo-framework-metadata"))
    implementation(project(":bo-framework-businessapi"))
    implementation(project(":bo-framework-endpoint-core"))
    implementation("org.springframework:spring-context:6.0.0-RC4")
    implementation("org.springframework:spring-beans:6.0.0-RC4")
    implementation("org.springframework:spring-web:6.0.0-RC4")
    implementation("org.springframework.boot:spring-boot-autoconfigure:3.0.0-RC2")
    implementation("org.springframework.boot:spring-boot-configuration-processor:3.0.0-RC2")
    implementation("org.glassfish.jersey.core:jersey-server:3.1.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.junit.platform:junit-platform-runner:1.9.1")
    testImplementation("org.mockito:mockito-core:4.9.0")
    testImplementation("jakarta.servlet:jakarta.servlet-api:6.0.0")
    testImplementation("org.springframework.boot:spring-boot-test:3.0.0-RC2")
    testImplementation("org.assertj:assertj-core:3.23.1")
}

description = "spring-jersey-endpoint-support"
