/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation(project(":bo-framework-jsr303-validation"))
    implementation("org.springframework.boot:spring-boot:3.0.0-RC2")
    implementation("org.springframework.boot:spring-boot-configuration-processor:3.0.0-RC2")
}

description = "spring-jsr303-validation"
