/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation(project(":bo-framework-metadata"))
    implementation(project(":bo-framework-repository"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.mockito:mockito-core:4.9.0")
    testImplementation("org.hamcrest:hamcrest:2.2")
}

description = "core-mapper"
