/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation("org.springframework:spring-beans:6.0.0-RC4")
    implementation("org.springframework:spring-context:6.0.0-RC4")
    implementation("org.springframework:spring-core:6.0.0-RC4")
    implementation(project(":bo-framework-metadata"))
    implementation(project(":bo-framework-repository"))
    implementation(project(":bo-framework-spring-jsr303-validation"))
    implementation("org.slf4j:slf4j-api:2.0.3")
    implementation("org.springframework.boot:spring-boot:3.0.0-RC2")
}

description = "spring-support-core"
