/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.14.0-rc3")
    implementation("org.slf4j:slf4j-api:2.0.3")
    implementation(project(":bo-framework-repository"))
    implementation(project(":bo-framework-core-mapper"))
    implementation(project(":bo-framework-exception-handling-core"))
    implementation(project(":bo-framework-metadata"))
    implementation(project(":bo-framework-query"))
    implementation("com.fasterxml.jackson.core:jackson-core:2.14.0-rc3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.14.0-rc3")
    implementation("jakarta.validation:jakarta.validation-api:3.0.2")
    implementation(project(":bo-framework-businessapi"))
    implementation("jakarta.inject:jakarta.inject-api:2.0.1")
    implementation(project(":bo-framework-dynamic"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.mockito:mockito-core:4.9.0")
    testImplementation("org.hamcrest:hamcrest:2.2")
    testImplementation("org.glassfish.hk2:hk2-locator:3.0.3")
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")
}

description = "endpoint-core"
