/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation("org.springframework:spring-context:6.0.0-RC4")
    implementation(project(":bo-framework-database-jpa"))
    implementation(project(":bo-framework-dynamic"))
    implementation(project(":bo-framework-businessapi"))
    implementation(project(":bo-framework-metadata"))
    implementation("org.springframework:spring-beans:6.0.0-RC4")
    implementation(project(":bo-framework-orika-mapper"))
    implementation(project(":bo-framework-repository"))
    implementation(project(":bo-framework-spring-support-core"))
    testImplementation(project(":bo-framework-database-mock"))
    testImplementation("org.hamcrest:hamcrest:2.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.junit.platform:junit-platform-runner:1.9.1")
}

description = "spring-database-jpa-support"
