/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation(project(":bo-framework-query"))
    implementation(project(":bo-framework-repository"))
    implementation(project(":bo-framework-exception-handling-core"))
    implementation(project(":bo-framework-validation-core"))
    implementation("org.junit.jupiter:junit-jupiter:5.9.1")
    implementation("org.slf4j:slf4j-api:2.0.3")
    implementation("org.hamcrest:hamcrest:2.2")
    implementation(project(":bo-framework-businessapi"))
}

description = "mock-common"
