/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation(project(":bo-framework-database-core"))
    implementation(project(":bo-framework-repository"))
    implementation(project(":bo-framework-core-mapper"))
    implementation(project(":bo-framework-metadata"))
    implementation(project(":bo-framework-query"))
    implementation("org.hibernate.orm:hibernate-core:6.1.5.Final")
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")
    implementation("jakarta.transaction:jakarta.transaction-api:2.0.1")
    implementation("org.slf4j:slf4j-api:2.0.3")
    implementation("org.glassfish.expressly:expressly:5.0.0")
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:4.0.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.mockito:mockito-core:4.9.0")
    testImplementation(project(":bo-framework-database-mock"))
    testImplementation(project(":bo-framework-mock-common"))
    testImplementation("org.hsqldb:hsqldb:2.7.1")
    testImplementation("org.hamcrest:hamcrest:2.2")
    testImplementation("org.hibernate.validator:hibernate-validator:8.0.0.Final")
}

description = "database-jpa"
