/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
    id("org.gradlex.extra-java-module-info") version "1.1"
}

extraJavaModuleInfo {
    failOnMissingModuleInfo.set(false)
    automaticModule("org.glassfish.jersey.core:jersey-server", "org.glassfish.jersey.core.jersey.server")
    automaticModule("org.glassfish.jersey.core:jersey-common", "org.glassfish.jersey.core.jersey.common")

    automaticModule("org.glassfish.jersey.test-framework:jersey-test-framework-core", "jersey.test.framework.core")
    automaticModule("org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-jetty", "jersey.test.framework.provider.jetty")
}

dependencies {
    implementation(project(":bo-framework-endpoint-jersey"))
    implementation(project(":bo-framework-endpoint-core"))
    implementation(project(":bo-framework-repository"))
    implementation(project(":bo-framework-businessapi"))
    implementation(project(":bo-framework-mock-common"))
    implementation(project(":bo-framework-database-mock"))
    implementation(project(":bo-framework-database-core"))
    implementation(project(":bo-framework-query"))
    implementation(project(":bo-framework-exception-handling-core"))
    implementation("com.google.inject.extensions:guice-servlet:5.1.0")
    implementation("org.hsqldb:hsqldb:2.7.1")
    implementation("org.hamcrest:hamcrest:2.2")
    implementation("org.mockito:mockito-core:4.9.0")
    implementation("com.google.inject:guice:5.1.0")
    implementation("jakarta.ws.rs:jakarta.ws.rs-api:3.1.0")
    implementation("jakarta.activation:jakarta.activation-api:2.1.0")
    implementation("org.junit.jupiter:junit-jupiter:5.9.1")
    implementation("org.glassfish.jersey.core:jersey-common:3.1.0")
    implementation("org.glassfish.jersey.core:jersey-server:3.1.0")
    implementation("org.glassfish.jersey.test-framework:jersey-test-framework-core:3.1.0")
    implementation("org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-jetty:3.1.0")
}

description = "endpoint-mock"
