/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")
    implementation("org.springframework.boot:spring-boot-starter-jersey:3.0.0-RC2")
    implementation("org.springframework.boot:spring-boot-starter-jetty:3.0.0-RC2")
    implementation("org.springframework.boot:spring-boot-starter-validation:3.0.0-RC2")
    implementation("org.springframework:spring-web:6.0.0-RC4")
    implementation(project(":bo-framework-spring-support-core"))
    implementation(project(":bo-framework-endpoint-jersey"))
    implementation(project(":bo-framework-orika-mapper-spring"))
    implementation(project(":bo-framework-database-jpa"))
    implementation(project(":bo-framework-database-core"))
    implementation(project(":bo-framework-spring-database-jpa-support"))
    implementation(project(":bo-framework-spring-jersey-endpoint-support"))
    implementation("org.springframework:spring-orm:6.0.0-RC4")
    implementation(project(":demo-domain"))
    implementation("org.springframework.boot:spring-boot-starter-actuator:3.0.0-RC2")
    runtimeOnly("org.hsqldb:hsqldb:2.7.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.0-RC2")
    testImplementation("io.rest-assured:spring-mock-mvc:5.3.0")
    testImplementation("org.junit.platform:junit-platform-launcher:1.9.1")
}

description = "spring-boot-jersey-demo"
