/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`

}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.spring.io/milestone/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "org.divy"
version = "0.0.19-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_19

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}