/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation(project(":bo-framework-repository"))
    implementation(project(":bo-framework-database-core"))
    implementation(project(":bo-framework-core-mapper"))
    implementation(project(":bo-framework-exception-handling-core"))
    implementation(project(":bo-framework-orika-mapper"))
    implementation(project(":bo-framework-orika-mapper-spring"))
    implementation(project(":bo-framework-database-jpa"))
    implementation(project(":bo-framework-metadata"))
    implementation(project(":bo-framework-spring-jersey-endpoint-support"))
    implementation(project(":bo-framework-spring-database-jpa-support"))
    implementation(project(":bo-framework-query"))
    implementation(project(":bo-framework-mock-common"))
    implementation(project(":bo-framework-dynamic"))
    implementation(project(":bo-framework-endpoint-core"))
    implementation(project(":bo-framework-endpoint-jersey"))
    implementation(project(":bo-framework-database-mock"))
    implementation(project(":bo-framework-endpoint-mock"))
    implementation(project(":bo-framework-businessapi"))
    implementation(project(":bo-framework-spring-support-core"))
    implementation(project(":bo-framework-spring-mvc-endpoint-support"))
    implementation(project(":demo-domain"))
    implementation(project(":bo-framework-spring-boot-mvc-demo"))
    implementation(project(":bo-framework-spring-boot-jersey-demo"))
    implementation(project(":bo-framework-validation-core"))
    implementation(project(":bo-framework-jsr303-validation"))
    implementation(project(":bo-framework-spring-jsr303-validation"))
}

description = "coverage-report"
