/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.divy.java-conventions")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-autoconfigure:3.0.0-RC2")
    implementation("org.springframework.boot:spring-boot-starter-web:3.0.0-RC2")
    implementation("org.springframework.boot:spring-boot-starter-actuator:3.0.0-RC2")
    implementation("org.springframework.boot:spring-boot-starter-tomcat:3.0.0-RC2")
    implementation("org.springframework.boot:spring-boot-starter-validation:3.0.0-RC2")
    implementation(project(":bo-framework-spring-support-core"))
    implementation(project(":bo-framework-orika-mapper-spring"))
    implementation(project(":bo-framework-database-jpa"))
    implementation(project(":bo-framework-database-core"))
    implementation(project(":bo-framework-spring-database-jpa-support"))
    implementation(project(":bo-framework-spring-jsr303-validation"))
    implementation("org.springframework:spring-orm:6.0.0-RC4")
    implementation("org.springframework.boot:spring-boot-actuator:3.0.0-RC2")
    implementation(project(":bo-framework-spring-mvc-endpoint-support"))
    implementation("org.springframework.hateoas:spring-hateoas:2.0.0-RC2")
    implementation(project(":demo-domain"))
    runtimeOnly("org.hsqldb:hsqldb:2.7.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.0-RC2")
    testImplementation("io.rest-assured:spring-mock-mvc:5.3.0")
}

description = "spring-boot-mvc-demo"
